#!/usr/bin/env bash
set -e

root="$(dirname $(realpath "$0"))"
mkdir -p build
cd build

# Configure
# 1. Explicitly set Release mode to ensure NDEBUG is defined (disables assertions).
# 2. Add -msimd128 for vectorization (supported by modern Chrome/Edge/Safari/Arc).
# 3. Disable shared libs to ensure static linking for WASM.
emcmake cmake ../HiGHS \
    -DCMAKE_BUILD_TYPE=Release \
    -DZLIB=OFF \
    -DFAST_BUILD=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DCMAKE_CXX_FLAGS="-msimd128"

# Build
# Compile the static library
emmake make -j8 libhighs

# Link
# Compile the linked code generated by make to JavaScript + WebAssembly.
# 'project.o' should be replaced with the make output for your project, and
# you may need to rename it if it isn't something emcc recognizes
# (for example, it might have a different suffix like 'project.so' or
# 'project.so.1', or no suffix like just 'project' for an executable).
# If the project output is a library, you may need to add your 'main.c' file
# here as well.
# [-Ox] represents build optimisations (discussed in the next section).
# 1. -O3: Aggressive optimizations.
# 2. -flto: Link Time Optimization (critical for C++).
# 3. -msimd128: Enable SIMD instructions.
# 4. --closure 1: Minify the glue JavaScript.
# 5. ALLOW_MEMORY_GROWTH=1: Essential for solvers that might need more RAM at runtime.
export EMCC_CLOSURE_ARGS="--jscomp_off=checkTypes"
emcc -O3 \
    -s EXPORTED_FUNCTIONS="@$root/exported_functions.json" \
    -s EXPORTED_RUNTIME_METHODS="['cwrap']" \
    -s MODULARIZE=1 \
    -s EXPORT_ES6=1 \
    -s ALLOW_MEMORY_GROWTH=1 \
    -s STACK_SIZE=4194304 \
    -flto \
    -msimd128 \
    --closure 1 \
    --pre-js "$root/src/pre.js" \
    --post-js "$root/src/post.js" \
    lib/*.a -o highs.js